### ISSUE TITLE
PDF payment schedules

### ISSUE THREAD

**Issue by TheDude70** [TommyAdyInc/MotoMenus-SaaS-API#5]
When printing the Payment Schedule(PS) PDF for the Units, they are listed individually (when more than one Unit being purchased) and then there is a `Total` option too at the bottom. However, when printing from the F&I section, the print outs are always on an individual basis. The `Total` option doesn't appear to be available as a finance option.

Should Total be an option for F&I or should Total not be listed on the PS?

**Comment by TommyAdy** [comment]
Not sure if I correctly posted an answer to this last night but I'll make sure I did by doing it again.  The total option should appear on the finance option page too.

**Comment by TheDude70** [comment]
Still have questions about the F&I PDF

I created a deal where want to purchase 1 new unit, and have two trade in units. When I print the F&I PDF only one trade shows, the active one on the Deal view. Is that how it should be, or what should the preferred way be? 
[f&i.pdf](https://github.com/TommyAdyInc/MotoMenus-SaaS-API/files/3935775/f.i.pdf)

- [ ] It's the active Unit and Active trade? 
- [ ] No trade if no Trade Allowance entered? 
- [ ] Active Unit and all trades?
- [ ] All units and all trades? 
- [ ] All units and only trades if Trade allowance specified?
- [ ] Other combo?

**Comment by TommyAdy** [comment]
The preferred way is to have both trades show on the PDF's.
𝑻𝒐𝒎𝒎𝒚 𝑨𝒅𝒚
208-405-9808Founder of The WriteBack Creator of Moto MenusAuthor of Expert Email Secrets

👉 Getting Sales In 72 Hours Masterclass
PLUS...if you're ready to REALLY crank up your sales using simple strategies, here is an action step to take now...
1. Want 10 Extra Sales In 72 Hours? Get 10+ customers overnight. expertemailsecrets.com 

    On Saturday, December 7, 2019, 07:24:53 PM MST, TheDude70 <notifications@github.com> wrote:  
 
 
Still have questions about the F&I PDF

I created a deal where want to purchase 1 new unit, and have two trade in units. When I print the F&I PDF only one trade shows, the active one on the Deal view. Is that how it should be, or what should the preferred way be?
f&i.pdf
   
   -  It's the active Unit and Active trade?
   -  No trade if no Trade Allowance entered?
   -  Active Unit and all trades?
   -  All units and all trades?
   -  All units and only trades if Trade allowance specified?
   -  Other combo?
