### ISSUE TITLE
Cash Specials

### ISSUE THREAD

**Issue by TheDude70** [TommyAdyInc/MotoMenus-SaaS-API#6]
@TommyAdy Could you explain Cash Specials to me please? When I enter anything in the discount fields it does not show on the PDF. Is Discount the discount amount or the discounted price?
Do the cash specials in any way affect the F&I? Do we need to do anything with the amounts entered in the calculations?

**Comment by TommyAdy** [comment]
The Cash Specials doesn't communicate with anything other than it's own calculations. The discount should be the price with a slash and then the discounted price. The cash discounts shouldn't affect the F&I or any other area.
𝑻𝒐𝒎𝒎𝒚 𝑨𝒅𝒚
208-405-9808Founder of The WriteBack Creator of Moto MenusAuthor of Expert Email Secrets

👉 Getting Sales In 72 Hours Masterclass
PLUS...if you're ready to REALLY crank up your sales using simple strategies, here is an action step to take now...
1. Want 10 Extra Sales In 72 Hours? Get 10+ customers overnight. expertemailsecrets.com 

    On Saturday, December 7, 2019, 07:36:06 PM MST, TheDude70 <notifications@github.com> wrote:  
 
 
Assigned #6 to @TommyAdy.
