### ISSUE TITLE
Failing tests on CircleCi

### ISSUE THREAD

**Issue by TheDude70** [TommyAdyInc/MotoMenus-SaaS-API#7]
Test failing on CircleCi while locally they all pass is because it fails on anywhere in the code I use `GlobalSetting::first()->document_fee;`

GlobalSetting is part of the `system` database. Not sure if the system dbase is part of the testing setup, or if it just does not run the Seeder as specified in the `DatabaseSeeder::class`

I don't want to add any unnecessary `app()->environment('testing')` checks if not needed, so if you have idea to solve making it work to pull that info from system dbase in testing that would be great. Else I'll need to add those extra checks.

**Comment by AustinMaddox** [comment]
Makes sense. Currently, seeding is not being run before unit tests. I'll work on that.

**Comment by AustinMaddox** [comment]
Alright, I overhauled the testing process. Should be all fixed up and run well locally and in CI/CD.

**Comment by TheDude70** [comment]
So I have an issue running tests locally and it is due to all the **\\\`** in the $this->execProcess(...) commands. When I remove the \ then it works correctly, but I'm not sure if that is because Windows only.

Edit: appears to be Windows issue as without those \ it fails on CircleCi

**Comment by AustinMaddox** [comment]
What is the error or problem you have?

**Comment by AustinMaddox** [comment]
I'm guessing you don't have `mysql-client` installed on your Windows machine which is required to run the commands like `mysql --execute \"DROP DATABASE IF EXISTS \`$database\`;\" ` and so forth.

**Comment by TheDude70** [comment]
Mysql runs just fine; the command runs fine when removing the \ (backslash from the exec command. When the backslash is present it throws error `unknown command`. I can only assume a difference between Windows and Linux.

**Comment by AustinMaddox** [comment]
I've pushed a few fixes. Let me know if things run better on Windows now.

**Comment by TheDude70** [comment]
@AustinMaddox This still has issues on Windows. When I copy the command and paste it into the Bootdocker teminal it runs fine. However, when I run it in a windows terminal/cmd window then it fails and it requires me to change wrapping the --excecute command in double quotes. When they are single quotes it fails. As I run all tests from within PhpStorm, which uses Windows cmd, it all fails, and as I pushed the commands wrapped in double quotes it's now failing on Linux :(

Edit: Testing a bit more, the issue is because of the backticks around the dbase name. If remove then it still fails because of the `-` in the name, however, if remove those or change to underscores then wrapping in double quotes seems to work on both systems. So maybe change the naming convention of dbase!?

**Comment by AustinMaddox** [comment]
Weird that it has been so difficult for us to find something that works cross-platform. 😕 

Changing the dashes (`-`) to underscores (`_`) in our database naming convention is fine. 👍 

It just bugs me, and still seems like a workaround. Backticks are important, so that is annoying. Especially if we wanted to have spaces in column names, or use dashes, or if we were to name a field with a possible reserved-word like "key", "order", or "values"... all of which require backticks when referring to them.

**Comment by TheDude70** [comment]
I believe I've found the solution where the same command will work on any system. Seems the key was to pass the command to `Process` as an array.
